#!/usr/bin/env bash
# This script ensures Nginx is listening on port 80

# remove the default nginx configuration
rm /etc/nginx/sites-enabled/default
#configure nginx to listen on port 80 for Ipv4 and Ips
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#restart nginx
service nginx restart
